### ISSUE TITLE
Bugged colors

### ISSUE THREAD

**Issue by LucaTheHacker** [bokub/gradient-string#2]
![Screenshot_1](https://user-images.githubusercontent.com/45915503/68349179-874dc180-00fc-11ea-9b2b-7a4517688641.png)
Seems that gradients are not working very well on my terminal
(should be rainbow)

**Comment by bokub** [comment]
Hi ! 
It looks like this is not an issue with my module, but one of these 2 possibilities:

1. Your terminal doesn't support [TrueColor](https://gist.github.com/XVilka/8346728)
2. Your terminal support TrueColor but it's not detected by [supports-color](https://github.com/chalk/supports-color)

What terminal do you use ?

**Comment by LucaTheHacker** [comment]
I'm using termius with premium subscription

Il gio 7 nov 2019, 17:27 Boris K <notifications@github.com> ha scritto:

**Comment by bokub** [comment]
Well, I suggest you open an issue on [supports-color](https://github.com/chalk/supports-color/issues) then
