### ISSUE TITLE
turning all integers into ,

### ISSUE THREAD

**Issue by niktooutis** [bokub/gradient-string#5]
<img width="400" alt="Screen Shot 2022-09-23 at 6 56 39 PM" src="https://user-images.githubusercontent.com/36449747/192013224-104275be-e6ce-4ce1-9ea0-11bb54c0e261.png">

<img width="330" alt="Screen Shot 2022-09-23 at 6 56 48 PM" src="https://user-images.githubusercontent.com/36449747/192013236-1035f780-5e6b-4fb1-abac-430ac3f546e3.png">

**Comment by bokub** [comment]
Of course it doesn't work, you're supposed to use gradient-string like this.

 ```diff
- console.log(gradient.retro`console ${6}`)
+ console.log(gradient.retro(`console ${6}`))
```

Please, next time read the documentation, or at least ask nicely if you need help, thanks.
